# Predict FPL Points
This notebook predicts FPL points using the data ingested and the model trained in previous notebooks.

## 1. Include required libraries

In [27]:
import joblib
import pandas as pd

## 2. Load Trained Model
We load the model that was trained in a previous notebook

In [28]:
# Load the trained model
model_filename = "../data/model/random_forest/20250330_110709/model.joblib"
model = joblib.load(model_filename)

## 3. Load Data
We load the features that were extracted and transformed from a previous notebook

In [32]:
# Load data
data_filename = "../data/processed/features/20250330_105203/features.parquet"
data = pd.read_parquet(data_filename)

# Show the data
data.head()

,fixture_code,team_code,opponent_team_code,kickoff_time,season_code,player_name,player_code,team_name,opponent_team_name,position,...,recent_team_clean_sheets,long_term_team_clean_sheets,recent_team_total_points,long_term_team_total_points,position_GK,position_DEF,position_MID,position_FWD,was_home_true,was_home_false
0,2367796,21,94,2024-02-26 20:00:00,2023_24,Lukasz Fabianski,37096,West Ham,Brentford,GK,...,0.0,4.0,150.0,782.0,1,0,0,0,1,0
1,2367796,21,94,2024-02-26 20:00:00,2023_24,Lukasz Fabianski,37096,West Ham,Brentford,GK,...,0.0,4.0,150.0,782.0,1,0,0,0,1,0
2,2367800,21,11,2024-03-02 15:00:00,2023_24,Lukasz Fabianski,37096,West Ham,Everton,GK,...,0.0,4.0,188.0,790.0,1,0,0,0,0,1
3,2367800,21,11,2024-03-02 15:00:00,2023_24,Lukasz Fabianski,37096,West Ham,Everton,GK,...,0.0,4.0,188.0,790.0,1,0,0,0,0,1
4,2367906,21,102,2024-05-11 14:00:00,2023_24,Lukasz Fabianski,37096,West Ham,Luton,GK,...,0.0,1.0,188.0,624.0,1,0,0,0,1,0

## 4. Predict FPL Points
We predict FPL points from the new data.

In [33]:
# Drop columns from data that are not in the features that the model was trained on
drop_cols = [col for col in data.columns if col not in model.feature_names_in_]
features = data.drop(columns=drop_cols)

# Make predictions
predictions = model.predict(features)

# Add predictions to the original data
data["predicted_points"] = predictions

# Show the data with predictions
data.head()

,fixture_code,team_code,opponent_team_code,kickoff_time,season_code,player_name,player_code,team_name,opponent_team_name,position,...,long_term_team_clean_sheets,recent_team_total_points,long_term_team_total_points,position_GK,position_DEF,position_MID,position_FWD,was_home_true,was_home_false,predicted_points
0,2367796,21,94,2024-02-26 20:00:00,2023_24,Lukasz Fabianski,37096,West Ham,Brentford,GK,...,4.0,150.0,782.0,1,0,0,0,1,0,0.1
1,2367796,21,94,2024-02-26 20:00:00,2023_24,Lukasz Fabianski,37096,West Ham,Brentford,GK,...,4.0,150.0,782.0,1,0,0,0,1,0,0.1
2,2367800,21,11,2024-03-02 15:00:00,2023_24,Lukasz Fabianski,37096,West Ham,Everton,GK,...,4.0,188.0,790.0,1,0,0,0,0,1,0.1
3,2367800,21,11,2024-03-02 15:00:00,2023_24,Lukasz Fabianski,37096,West Ham,Everton,GK,...,4.0,188.0,790.0,1,0,0,0,0,1,0.0
4,2367906,21,102,2024-05-11 14:00:00,2023_24,Lukasz Fabianski,37096,West Ham,Luton,GK,...,1.0,188.0,624.0,1,0,0,0,1,0,0.2

## 5. Clean Data
We clean the data and select which columns we want to export for visualisation.

In [36]:
# Create a DataFrame with the predictions and the target variable
cleaned_data = data

cleaned_data.head()

,fixture_code,team_code,opponent_team_code,kickoff_time,season_code,player_name,player_code,team_name,opponent_team_name,position,...,long_term_team_clean_sheets,recent_team_total_points,long_term_team_total_points,position_GK,position_DEF,position_MID,position_FWD,was_home_true,was_home_false,predicted_points
0,2367796,21,94,2024-02-26 20:00:00,2023_24,Lukasz Fabianski,37096,West Ham,Brentford,GK,...,4.0,150.0,782.0,1,0,0,0,1,0,0.1
1,2367796,21,94,2024-02-26 20:00:00,2023_24,Lukasz Fabianski,37096,West Ham,Brentford,GK,...,4.0,150.0,782.0,1,0,0,0,1,0,0.1
2,2367800,21,11,2024-03-02 15:00:00,2023_24,Lukasz Fabianski,37096,West Ham,Everton,GK,...,4.0,188.0,790.0,1,0,0,0,0,1,0.1
3,2367800,21,11,2024-03-02 15:00:00,2023_24,Lukasz Fabianski,37096,West Ham,Everton,GK,...,4.0,188.0,790.0,1,0,0,0,0,1,0.0
4,2367906,21,102,2024-05-11 14:00:00,2023_24,Lukasz Fabianski,37096,West Ham,Luton,GK,...,1.0,188.0,624.0,1,0,0,0,1,0,0.2

## 6. Write Data

In [ ]:
from datetime import datetime
import os

# Define output directory
# We define the directory where the processed data will be saved.
data_source = "predictions"
current_datetime = datetime.now().strftime("%Y%m%d_%H%M%S")
output_dir = f"../data/processed/{data_source}/{current_datetime}"
filename = "predictions.parquet"
filepath = os.path.join(output_dir, filename)

if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Create the directory if it doesn't exist
# We create the directory if it doesn't exist.
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# # Write the transformed DataFrames to Parquet files
# # We save the processed data as parquet files.
cleaned_data.to_parquet(filepath, index=False)

print(f"Predictions complete! Data saved to {output_dir}")

Predictions complete!